production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['REDMINE_DB_DATABASE'] %>
  host: <%= ENV['REDMINE_DB_HOST'] %>
  username: <%= ENV['REDMINE_DB_USERNAME'] %>
  password: <%= ENV['REDMINE_DB_PASSWORD'] %>
  pool: 5
